### ISSUE TITLE
[Bug] autoconf error on brew install obi

### ISSUE THREAD

**Issue by jshrake** [Oblong/homebrew-tools#1]
A user reports the following experience when installing via homebrew:

```
==> Installing obi from oblong/homebrew-tools
==> Downloading https://github.com/Oblong/obi/releases/download/v2.0.1/oblong-obi-2.0.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/obi-2.0.1.tar.gz
==> Downloading https://pypi.python.org/packages/source/d/docopt/docopt-0.6.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/obi--docopt-0.6.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/obi/2.0.1/libexec/vendor --single-ve
==> Downloading https://pypi.python.org/packages/source/e/ecdsa/ecdsa-0.13.tar.gz
Already downloaded: /Library/Caches/Homebrew/obi--ecdsa-0.13.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/obi/2.0.1/libexec/vendor --single-ve
==> Downloading https://pypi.python.org/packages/source/F/Fabric/Fabric-1.10.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/obi--Fabric-1.10.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/obi/2.0.1/libexec/vendor --single-ve
==> Downloading https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.8.tar.gz
Already downloaded: /Library/Caches/Homebrew/obi--Jinja2-2.8.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/obi/2.0.1/libexec/vendor --single-ve
==> Downloading https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz
Already downloaded: /Library/Caches/Homebrew/obi--MarkupSafe-0.23.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/obi/2.0.1/libexec/vendor --single-ve
==> Downloading https://pypi.python.org/packages/source/p/paramiko/paramiko-1.15.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/obi--paramiko-1.15.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/obi/2.0.1/libexec/vendor --single-ve
==> Downloading https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/obi--pycrypto-2.6.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/obi/2.0.1/libexec/vendor --single-ve
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 278, in run
    raise RuntimeError("autoconf error")
RuntimeError: autoconf error
```

**Comment by jshrake** [comment]
User is on OSX Yosemite + Xcode 7

**Comment by taimur38** [comment]
@jshrake running into this on yosemite and xcode 7.1

**Comment by tomjakubowski** [comment]
maybe related? https://github.com/pypa/pip/pull/1934 

the obi recipe sometimes uses the system python (and therefore system pip) if the OS X version is <= Snow Leopard <https://github.com/Oblong/homebrew-tools/blob/master/obi.rb#L8>. And perhaps pip in Yosemite is broken with respect to the linked issue.

**Comment by tomjakubowski** [comment]
ah, doh. pip isn't used by the homebrew recipe at all.

**Comment by taimur38** [comment]
```
2015-11-02 10:30:17 -0800

python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/obi/3.0.0/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install
running build
running build_py
creating build
creating build/lib.macosx-10.10-intel-2.7
creating build/lib.macosx-10.10-intel-2.7/Crypto
copying lib/Crypto/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto
copying lib/Crypto/pct_warnings.py -> build/lib.macosx-10.10-intel-2.7/Crypto
creating build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/hashalgo.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/HMAC.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/MD2.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/MD4.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/MD5.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/RIPEMD.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/SHA.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/SHA224.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/SHA256.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/SHA384.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
copying lib/Crypto/Hash/SHA512.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Hash
creating build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/AES.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/ARC2.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/ARC4.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/blockalgo.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/Blowfish.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/CAST.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/DES.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/DES3.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/PKCS1_OAEP.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/PKCS1_v1_5.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
copying lib/Crypto/Cipher/XOR.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Cipher
creating build/lib.macosx-10.10-intel-2.7/Crypto/Util
copying lib/Crypto/Util/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Util
copying lib/Crypto/Util/_number_new.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Util
copying lib/Crypto/Util/asn1.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Util
copying lib/Crypto/Util/Counter.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Util
copying lib/Crypto/Util/number.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Util
copying lib/Crypto/Util/py21compat.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Util
copying lib/Crypto/Util/py3compat.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Util
copying lib/Crypto/Util/randpool.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Util
copying lib/Crypto/Util/RFC1751.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Util
copying lib/Crypto/Util/winrandom.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Util
creating build/lib.macosx-10.10-intel-2.7/Crypto/Random
copying lib/Crypto/Random/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random
copying lib/Crypto/Random/_UserFriendlyRNG.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random
copying lib/Crypto/Random/random.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random
creating build/lib.macosx-10.10-intel-2.7/Crypto/Random/Fortuna
copying lib/Crypto/Random/Fortuna/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random/Fortuna
copying lib/Crypto/Random/Fortuna/FortunaAccumulator.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random/Fortuna
copying lib/Crypto/Random/Fortuna/FortunaGenerator.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random/Fortuna
copying lib/Crypto/Random/Fortuna/SHAd256.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random/Fortuna
creating build/lib.macosx-10.10-intel-2.7/Crypto/Random/OSRNG
copying lib/Crypto/Random/OSRNG/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random/OSRNG
copying lib/Crypto/Random/OSRNG/fallback.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random/OSRNG
copying lib/Crypto/Random/OSRNG/nt.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random/OSRNG
copying lib/Crypto/Random/OSRNG/posix.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random/OSRNG
copying lib/Crypto/Random/OSRNG/rng_base.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Random/OSRNG
creating build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest
copying lib/Crypto/SelfTest/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest
copying lib/Crypto/SelfTest/st_common.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest
creating build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/common.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_AES.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_ARC2.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_ARC4.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_Blowfish.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_CAST.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_DES.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_DES3.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_pkcs1_15.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_XOR.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Cipher
creating build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/common.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_HMAC.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_MD2.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_MD4.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_MD5.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_RIPEMD.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_SHA.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_SHA224.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_SHA256.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_SHA384.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_SHA512.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Hash
creating build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Protocol
copying lib/Crypto/SelfTest/Protocol/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Protocol
copying lib/Crypto/SelfTest/Protocol/test_AllOrNothing.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Protocol
copying lib/Crypto/SelfTest/Protocol/test_chaffing.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Protocol
copying lib/Crypto/SelfTest/Protocol/test_KDF.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Protocol
copying lib/Crypto/SelfTest/Protocol/test_rfc1751.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Protocol
creating build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/PublicKey
copying lib/Crypto/SelfTest/PublicKey/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/PublicKey
copying lib/Crypto/SelfTest/PublicKey/test_DSA.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/PublicKey
copying lib/Crypto/SelfTest/PublicKey/test_ElGamal.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/PublicKey
copying lib/Crypto/SelfTest/PublicKey/test_importKey.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/PublicKey
copying lib/Crypto/SelfTest/PublicKey/test_RSA.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/PublicKey
creating build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random
copying lib/Crypto/SelfTest/Random/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random
copying lib/Crypto/SelfTest/Random/test__UserFriendlyRNG.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random
copying lib/Crypto/SelfTest/Random/test_random.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random
copying lib/Crypto/SelfTest/Random/test_rpoolcompat.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random
creating build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/Fortuna
copying lib/Crypto/SelfTest/Random/Fortuna/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/Fortuna
copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/Fortuna
copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/Fortuna
copying lib/Crypto/SelfTest/Random/Fortuna/test_SHAd256.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/Fortuna
creating build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/test_fallback.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/test_generic.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/test_nt.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/test_posix.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/test_winrandom.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Random/OSRNG
creating build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Util
copying lib/Crypto/SelfTest/Util/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Util
copying lib/Crypto/SelfTest/Util/test_asn1.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Util
copying lib/Crypto/SelfTest/Util/test_Counter.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Util
copying lib/Crypto/SelfTest/Util/test_number.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Util
copying lib/Crypto/SelfTest/Util/test_winrandom.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Util
creating build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Signature
copying lib/Crypto/SelfTest/Signature/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Signature
copying lib/Crypto/SelfTest/Signature/test_pkcs1_15.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Signature
copying lib/Crypto/SelfTest/Signature/test_pkcs1_pss.py -> build/lib.macosx-10.10-intel-2.7/Crypto/SelfTest/Signature
creating build/lib.macosx-10.10-intel-2.7/Crypto/Protocol
copying lib/Crypto/Protocol/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Protocol
copying lib/Crypto/Protocol/AllOrNothing.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Protocol
copying lib/Crypto/Protocol/Chaffing.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Protocol
copying lib/Crypto/Protocol/KDF.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Protocol
creating build/lib.macosx-10.10-intel-2.7/Crypto/PublicKey
copying lib/Crypto/PublicKey/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/PublicKey
copying lib/Crypto/PublicKey/_DSA.py -> build/lib.macosx-10.10-intel-2.7/Crypto/PublicKey
copying lib/Crypto/PublicKey/_RSA.py -> build/lib.macosx-10.10-intel-2.7/Crypto/PublicKey
copying lib/Crypto/PublicKey/_slowmath.py -> build/lib.macosx-10.10-intel-2.7/Crypto/PublicKey
copying lib/Crypto/PublicKey/DSA.py -> build/lib.macosx-10.10-intel-2.7/Crypto/PublicKey
copying lib/Crypto/PublicKey/ElGamal.py -> build/lib.macosx-10.10-intel-2.7/Crypto/PublicKey
copying lib/Crypto/PublicKey/pubkey.py -> build/lib.macosx-10.10-intel-2.7/Crypto/PublicKey
copying lib/Crypto/PublicKey/RSA.py -> build/lib.macosx-10.10-intel-2.7/Crypto/PublicKey
creating build/lib.macosx-10.10-intel-2.7/Crypto/Signature
copying lib/Crypto/Signature/__init__.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Signature
copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Signature
copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.macosx-10.10-intel-2.7/Crypto/Signature
running build_ext
running build_configure
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/obi--pycrypto20151102-63719-nm367w/pycrypto-2.6.1':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "setup.py", line 456, in <module>
    core.setup(**kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 53, in run
    return _install.run(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
    self.run_command('build')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 251, in run
    self.run_command(cmd_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 278, in run
    raise RuntimeError("autoconf error")
RuntimeError: autoconf error

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 28643e4711fb5a0f3eb152f4a2023bf440d47f0f
Last commit: 44 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.10.5-x86_64
Xcode: 7.1
CLT: N/A
GCC-4.2: build 0
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45, 1.8.0_25, 1.6.0_65-b14-466.1

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /System/Library/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/libyaml/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
HOMEBREW_SDKROOT: 
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by taimur38** [comment]
to fix:

```
brew doctor

Warning: Xcode 7 lacks the 10.10 SDK which can cause some builds to fail.
We recommend installing the Command Line Tools with:
  xcode-select --install
to resolve this issue.

xcode-select install
```

**Comment by tomjakubowski** [comment]
closing
